"""Modelo proveedores

Revision ID: 3f4e13c2322d
Revises: 
Create Date: 2026-03-29 13:52:59.850561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4e13c2322d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MateriaPrima',
    sa.Column('id_materia', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('stock_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stock_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unidad_medida', sa.String(length=20), nullable=True),
    sa.Column('estatus', sa.Enum('Activo', 'Inactivo'), nullable=True),
    sa.PrimaryKeyConstraint('id_materia')
    )
    op.create_table('Modulos',
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('nombre_modulo', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_modulo')
    )
    op.create_table('Perfiles',
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('nombre_perfil', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_perfil'),
    sa.UniqueConstraint('nombre_perfil')
    )
    op.create_table('Proveedores',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('num_unico_prov', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('domicilio', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.Column('estatus', sa.Enum('Activo', 'Inactivo'), nullable=True),
    sa.PrimaryKeyConstraint('id_proveedor'),
    sa.UniqueConstraint('num_unico_prov')
    )
    op.create_table('Perfil_Modulo',
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('id_modulo', sa.Integer(), nullable=False),
    sa.Column('permiso_escritura', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_modulo'], ['Modulos.id_modulo'], ),
    sa.ForeignKeyConstraint(['id_perfil'], ['Perfiles.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_perfil', 'id_modulo')
    )
    op.create_table('Usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.Column('estatus', sa.Enum('Activo', 'Inactivo'), nullable=True),
    sa.Column('id_perfil', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['Perfiles.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('fs_uniquifier'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Clientes',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('direccion_envio', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Clientes')
    op.drop_table('Usuarios')
    op.drop_table('Perfil_Modulo')
    op.drop_table('Proveedores')
    op.drop_table('Perfiles')
    op.drop_table('Modulos')
    op.drop_table('MateriaPrima')
    # ### end Alembic commands ###
